In [2]:
import numpy as np


#Dataset
np_olympic_country=np.array([ 'GBR', 'Chine', 'RUS', 'US', 'KOR', 'JPN', 'GER'])
np_olympic_country_gold=np.array([29,38,24,46,13,7,11])
np_olympic_country_silver=np.array([17,28,25,28,8,14,11]) 
np_olympic_country_Bronze=np.array([19,22,32,29,7,17,14])


# 1.find the country index with maximum gold

In [5]:
max_gold_index = np.argmax(np_olympic_country_gold)

# Find the country with the maximum gold medals
country_with_max_gold = np_olympic_country[max_gold_index]

print("Index of the country with the maximum gold medals:", max_gold_index)

Index of the country with the maximum gold medals: 3


# 2. Print Country with Maximum gold

In [6]:
print("The country with the maximum gold medals is:", country_with_max_gold)

The country with the maximum gold medals is: US


# 3. Find countries with more than 20 gold medals

In [7]:
countries_with_more_than_20_gold = np_olympic_country[np_olympic_country_gold > 20]

print("Countries with more than 20 gold medals:", countries_with_more_than_20_gold)

Countries with more than 20 gold medals: ['GBR' 'Chine' 'RUS' 'US']


# 4. Evaluate the dataset and print the medal:
1. print each country name with number of gold medals
2. print each country name with total number of medals

In [9]:
total_medals = np_olympic_country_gold + np_olympic_country_silver + np_olympic_country_Bronze

for i in range(len(np_olympic_country)):
    country = np_olympic_country[i]
    gold_medals = np_olympic_country_gold[i]
    total = total_medals[i]
    print(f"Country: {country}, Gold Medals: {gold_medals}, Total Medals: {total}")

Country: GBR, Gold Medals: 29, Total Medals: 65
Country: Chine, Gold Medals: 38, Total Medals: 88
Country: RUS, Gold Medals: 24, Total Medals: 81
Country: US, Gold Medals: 46, Total Medals: 103
Country: KOR, Gold Medals: 13, Total Medals: 28
Country: JPN, Gold Medals: 7, Total Medals: 38
Country: GER, Gold Medals: 11, Total Medals: 36


# 1. Create a 3x3x3 array with random values

In [11]:
random_array = np.random.rand(3, 3, 3)

print(random_array)

[[[0.62308796 0.13943331 0.55694291]
  [0.35796393 0.42013232 0.60168373]
  [0.97151217 0.95359749 0.41909693]]

 [[0.34523421 0.10327741 0.19167654]
  [0.82345041 0.76584707 0.45872735]
  [0.79088126 0.03639934 0.46418171]]

 [[0.14537172 0.62093959 0.72466029]
  [0.93600868 0.90197481 0.64481877]
  [0.79756638 0.28804259 0.05151478]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [12]:
matrix = np.zeros((5, 5), dtype=int)

# Set values 1, 2, 3, and 4 just below the diagonal
for i in range(1, 5):
    matrix[i, i - 1] = i

print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [13]:
checkerboard = np.zeros((8, 8), dtype=int)

# Set every other element (even rows and columns) to 1
checkerboard[::2, ::2] = 1  # Even rows and even columns
checkerboard[1::2, 1::2] = 1  # Odd rows and odd columns

print(checkerboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# 4. Normalize a 5x5 random matrix

In [14]:
random_matrix = np.random.rand(5, 5)

# Normalize the matrix to have values between 0 and 1
min_val = random_matrix.min()
max_val = random_matrix.max()
normalized_matrix = (random_matrix - min_val) / (max_val - min_val)

print("Original Random Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)

Original Random Matrix:
[[0.02794823 0.24406509 0.42886658 0.094665   0.01898499]
 [0.90544831 0.30589867 0.79367495 0.14250716 0.45941695]
 [0.85235365 0.62609587 0.69326722 0.2868567  0.9257869 ]
 [0.23934562 0.3249822  0.5788042  0.95327015 0.97917556]
 [0.81509878 0.27500367 0.69989031 0.7076251  0.93983336]]

Normalized Matrix:
[[0.00933486 0.23441191 0.42687525 0.0788177  0.        ]
 [0.92321602 0.2988091  0.80680855 0.12864339 0.45869224]
 [0.86792007 0.63228166 0.70223793 0.27897766 0.94439785]
 [0.22949677 0.31868383 0.58302927 0.97302056 1.        ]
 [0.82912061 0.2666332  0.7091356  0.71719108 0.95902668]]


# 5. How to find common values between two arrays?

In [15]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

common_values = np.intersect1d(array1, array2)

print(common_values)

[3 4 5]


# 6.How to get the dates of yesterday, today and tomorrow?

In [16]:
from datetime import datetime, timedelta

# Get the current date (today)
today = datetime.now().date()

# Calculate the dates for yesterday and tomorrow
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

# Format the dates as strings
today_str = today.strftime("%Y-%m-%d")
yesterday_str = yesterday.strftime("%Y-%m-%d")
tomorrow_str = tomorrow.strftime("%Y-%m-%d")

# Print the dates
print("Yesterday:", yesterday_str)
print("Today:", today_str)
print("Tomorrow:", tomorrow_str)


Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


# 7. Consider two random array A and B, check if they are equal

In [17]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

# Check if the arrays A and B are equal
are_equal = np.array_equal(A, B)

if are_equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")

Arrays A and B are not equal.


# 8.Create random vector of size 10 and replace the maximum value by 0

In [18]:
# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value in the vector
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Random Vector with Maximum Value Replaced:")
print(random_vector)


Random Vector with Maximum Value Replaced:
[0.76156187 0.30929224 0.9738237  0.         0.14200735 0.93101534
 0.05401913 0.15873555 0.51180373 0.4342875 ]


# 9. How to print all the values of an array?

In [19]:
my_array = np.array([1, 2, 3, 4, 5])

# Using a loop to iterate through the array elements
for value in my_array:
    print(value)

# Using numpy.nditer to iterate through the array elements
for value in np.nditer(my_array):
    print(value)

1
2
3
4
5
1
2
3
4
5


# 10.Subtract the mean of each row of a matrix

In [20]:
matrix = np.random.rand(4, 5)

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the row means from the original matrix
matrix_minus_means = matrix - row_means

print("Original Matrix:")
print(matrix)
print("\nMatrix with Row Means Subtracted:")
print(matrix_minus_means)

Original Matrix:
[[0.54203332 0.65410975 0.11684546 0.19134041 0.00196833]
 [0.93083248 0.88195226 0.49941759 0.67743799 0.95278586]
 [0.27261191 0.70330494 0.25981242 0.63171497 0.10782144]
 [0.18418106 0.73692412 0.1655653  0.10489987 0.37404216]]

Matrix with Row Means Subtracted:
[[ 0.24077386  0.35285029 -0.18441399 -0.10991904 -0.29929112]
 [ 0.14234724  0.09346702 -0.28906764 -0.11104724  0.16430063]
 [-0.12244122  0.3082518  -0.13524071  0.23666183 -0.2872317 ]
 [-0.12894144  0.42380162 -0.1475572  -0.20822263  0.06091966]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [21]:
vector = np.array([1, 2, 3, 4, 5])

# Second vector with indices (assuming indices are valid and within the vector's range)
indices = np.array([1, 3, 4])

# Create a mask to identify unique indices
unique_indices = np.unique(indices)

# Add 1 to the elements at unique indices
vector[unique_indices] += 1

print("Original Vector:")
print(vector)


Original Vector:
[1 3 3 5 6]


# 12.How to get the diagonal of a dot product?

In [22]:
matrix_A = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix_B = np.array([[9, 8, 7],
                     [6, 5, 4],
                     [3, 2, 1]])

# Compute the dot product of the two matrices
dot_product = np.dot(matrix_A, matrix_B)

# Extract the diagonal elements from the dot product
diagonal = np.diag(dot_product)

print("Original Dot Product Matrix:")
print(dot_product)
print("\nDiagonal of the Dot Product:")
print(diagonal)

Original Dot Product Matrix:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Diagonal of the Dot Product:
[30 69 90]


# 13.How to find the most frequent value in an array?

np.random.randint(0,10,50)

In [24]:
np.random.randint(0,10,50)
my_array = np.array([2, 9, 5, 6, 5, 9, 5, 8, 9, 2, 6, 1, 8, 6, 4, 4, 8, 4, 4, 8, 2, 2,
                     5, 9, 6, 6, 1, 0, 6, 1, 8, 4, 4, 9, 5, 9, 9, 2, 4, 5, 0, 6, 5, 2,
                     8, 2, 1, 9, 0, 0])

# Use NumPy to find the most frequent value
most_common_value = np.bincount(my_array).argmax()

print("Most frequent value:", most_common_value)

Most frequent value: 9


# 14.How to get the n largest values of an array

In [3]:
arr = np.array([4, 2, 9, 7, 5, 1, 8])
n = 3

largest_values = np.partition(arr, -n)[-n:]
print(largest_values)

[7 9 8]


# 15.How to create a record array from a regular array?

In [5]:
regular_array = np.array([("Jay", 23, 5.6), ("Vaibhav", 24, 6.0), ("Chiraj", 28, 5.9)], dtype=object)

dtype = np.dtype([('name', 'U10'), ('age', int), ('height', float)])

record_array = np.array([tuple(row) for row in regular_array], dtype=dtype)

print(record_array['name'])
print(record_array['age'])
print(record_array['height'])

['Jay' 'Vaibhav' 'Chiraj']
[23 24 28]
[5.6 6.  5.9]


# 16. How to swap two rows of an array?

In [6]:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])


row1_index = 0 
row2_index = 2  

# Swap the rows
array[row1_index], array[row2_index] = array[row2_index], array[row1_index]

print(array)

[[7 8 9]
 [4 5 6]
 [7 8 9]]


# 17. Write python code to reshape to the next dimension of numpy array?

np.array([[23,34,121],[23,22,67],[686,434,123]])
x

array([[ 23, 14, 121],
       [23, 22, 67],
       [686, 434, 123]])

In [7]:
x = np.array([[23, 34, 121],
              [23, 22, 67],
              [686, 434, 123]])

row_sums = np.sum(x, axis=1)

reshaped_x = np.copy(x) 
reshaped_x[np.arange(len(x)), np.argmax(x, axis=1)] = row_sums

print(reshaped_x)

[[  23   34  178]
 [  23   22  112]
 [1243  434  123]]
